### ISSUE TITLE
Support for multiple currencies

### ISSUE THREAD

**Issue by sulemankm** [Eqonomize/Eqonomize#10]
Hi, I've just started using Eqonomize.  So far it looks great for managing my household budget.  However, support for multiple currencies seems to be missing from the software, which in my view is a serious omission.

The base currency of my country is not USD and there is no way to tell Eqonomize which currency should it use for my accounts.

So plz add support for other currencies for each account as I think this is an essential feature.

**Comment by hanna-kn** [comment]
Eqonomize! currently uses the currency (symbol) configured as default for the user/system. Support for different currencies for each account is on my todo list, but it will require quite a lot of work and I have personally no use for it since all my accounts are in SEK. It will however be added eventually.

**Comment by selfus** [comment]
This all could be done under a settings page

**Comment by hanna-kn** [comment]
It would be simple to add an option for selection of a single currency (and the associated currency symbol placement, number of decimals, etc.), but I prefer to refer the user to the appropriate global option for the operating system (from additional settings in region settings of Windows and $LC_MONETARY on Linux) or desktop environment (Regional Settings->Formats in the system settings of KDE, under "Region and Language" in the Gnome Control Center and in the "Language Support" administration window of Ubuntu). When multiple simultaneous currencies are supported, the currency selection will of course be added to the settings page of each account.

**Comment by sulemankm** [comment]
Hi hanna, if you don't have time for this, I could try to add this support but I don't know the design of this software.  If you could give me some hints on how in the code it should be added, I would try to implement and submit a pull request.

**Comment by hanna-kn** [comment]
I'm still not sure if we're talking about configurable currency for the whole application (which is already configurable on operating system level, just as for most other software) or for each account. 

Configurable currency for each account requires code changes and additions in many places and multiple important design decisions (mostly concerning the conversion between currencies, which is needed for transfers between accounts and general statistics) and it would currently probably not be wise for anyone but me to attempt it. At the moment I'm focusing my efforts on my other project (https://github.com/Qalculate), but that will soon change.

**Comment by sulemankm** [comment]
I was talking about currency configuration per account.

**Comment by hanna-kn** [comment]
Done. 
(Extensive testing, manage currencies window and file export/import adaptation remains)

**Comment by vnnv** [comment]
Hi Hanna, 
it seem there are missing files:

> qmake
WARNING: Failure to find: src/editcurrencydialog.cpp
WARNING: Failure to find: src/editcurrencydialog.h

**Comment by hanna-kn** [comment]
The missing files have now been added.

**Comment by vnnv** [comment]
Thanks a lot :) I'll try this neat feature :)

**Comment by vnnv** [comment]
The feature looks very cool! :) I personally use 4 different currencies and till now used some exotic transactions to keep the accounts in order :) Thanks a lot for this feature :) will test is :)

**Comment by sulemankm** [comment]
Great!
