### ISSUE TITLE
Manpage for Linux systems

### ISSUE THREAD

**Issue by fabiomt** [Eqonomize/Eqonomize#100]
Hello,

It would be nice if you provide a manpage for your software, I'm attached a simple one that could be a good starting point.

Thanks for your work on this, it's a great software.

[manpage.zip](https://github.com/Eqonomize/Eqonomize/files/4875378/manpage.zip)

**Comment by hanna-kn** [comment]
Thanks.

I've now added a man page to the git repository (https://raw.githubusercontent.com/Eqonomize/Eqonomize/master/data/eqonomize.1).
