### ISSUE TITLE
Link transactions

### ISSUE THREAD

**Issue by fabianski7** [Eqonomize/Eqonomize#102]
A transaction split with an expense and a revenue (cashback) are created the right way, this is the first finance program I use that does it right, congratulations.

The only thing I think is necessary to complement this function is to create a link between the two entries that were created in this example I quoted. 
Currently, Economize shows a warning at the bottom that that transaction is part of a division ([here](https://upload.vaa.red/nu2m1#Ug0W5VXuhs8eK9oRZrNrKo6J6xLGHaqK) and [here](https://upload.vaa.red/2motmZ#X7Dmciijntukqthgism3AXjgQswPyBmL)), this is already great and necessary, but there should also be the possibility to click on this information and be displayed the details of that divided transaction, like the other part. 
This is already possible (your program is amazing!) through the menu [`Transactions -> Edit Split Transaction`](https://upload.vaa.red/Yh91e#gPLMbRCYEnwdmtpn61iNB4saVod7FCTM), so clicking on this information would basically be a shortcut to this menu item that would [display this screen](https://upload.vaa.red/21fhNi#S5NEvLoFHCdxXgifHtDmhAB42vf8GkcF).

I believe this is more of a visual fix than a feature request.
I hope you were able to pass on my suggestion in a clear way. 

Have a good day!

**Comment by hanna-kn** [comment]
Done.

Notice however that the "Edit..." ("Editar...") button (changes from "Apply") also opens the split transaction dialog (with modifications applied to the selected transaction).
