### ISSUE TITLE
Navigation in dropdown fields

### ISSUE THREAD

**Issue by ratsnet** [Eqonomize/Eqonomize#12]
Currently, when entering a Dropdown field like Category in the expenses form, arrow up and arrow down select the previous or next value and jump in a field before or the one after.

Expected behaviour: arrow up / down can be uses multiple times to navigate to a matching value and only tabulator jumps out to the next field.

Running Eqonomize! 1.0 Beta 1 on Debian

**Comment by hanna-kn** [comment]
Fixed.

**Comment by ratsnet** [comment]
That was fast, thank you @hanna-kn!
