### ISSUE TITLE
Absturz

### ISSUE THREAD

**Issue by xyz0815-ph** [Eqonomize/Eqonomize#123]
Hallo,

ich habe einen Kauf einer Aktie fälschlicherweise für den 22.03.2021 verdatet. Das ist mir später aufgefallen, ich habe unter "Terminplan" den falschen Eintrag mit "Bearbeite Terminplan (Wiederholung)" geöffnet, das Datum auf 22.02.2021 geändert und mit "OK" bestätigt. Dabei stürzte Eqonomize (v1.4.3) ab. Ich habe dies mit einem anderen Kaufbetrag und Anzahl von Aktien nachgestellt, wieder kam es zu einem Absturz ohne Fehlermeldung.

Freundliche Grüße

**Comment by hanna-kn** [comment]
Should be fixed in version 1.5.2 (released today).
