### ISSUE TITLE
Proposal - a slight change in edit transaction form

### ISSUE THREAD

**Issue by vnnv** [Eqonomize/Eqonomize#124]
Hello Hanna. Thanks for this very useful application. I use it for more than 10 years and it is great. 
I have,  let's say a feature request. 
Is it possible for the future version in `Transaction Edit Widget` the control for the comment to be changed to a multi-line edit, so the user to be able to enter comments on more than 1 line. I experimented with changing `QLineEdit` with `QTextEdit` and this is the result:
![eq - feature request - Screenshot_2021-05-05_13-46-21](https://user-images.githubusercontent.com/4255342/117130624-fe731d00-ada8-11eb-80e8-81bedfe8a3c5.png)

What do you think about that idea ?

**Comment by vnnv** [comment]
Hello Hanna, thanks for the improvement. 
I try to use this multi-line comments but unfortunately can not use new line in the component. How can I use CR in the field ? Thanks

**Comment by hanna-kn** [comment]
I'm a bit hesitant about changing the behaviour of the Enter key in the dialog. I've now however enabled use of the Enter key for new line in comments (and instead disabled tab input).

Shift + Enter should always work regardless of any changes I make.

**Comment by vnnv** [comment]
:) Wow, that was fast and it is working. Now I can make multiline comments. Ctrl-Enter saves the transaction. 
Could you please make the cotrol for the comment to be resized if the windows is higher ? here is a screenshot if the transaction window is bigger. 
![Screenshot_2021-09-10_13-36-04](https://user-images.githubusercontent.com/4255342/132841096-5fb8d37a-d360-423e-9076-dc5f5b99858a.png)

**Comment by vnnv** [comment]
Thank you very much! :) Works very well. I think this ticket can be closed :)
