### ISSUE TITLE
Font in Screenshot

### ISSUE THREAD

**Issue by culso** [Eqonomize/Eqonomize#132]
Not really an issue, but does anyone know the name of the font used on the screenshot on main page of this repo? ([link](https://raw.githubusercontent.com/Eqonomize/eqonomize.github.io/master/images/accounts.png))
The main thing that I'm looking for is a serif font with those "hanging numbers" or "non-lining figures", e.g. a "7" hangs lower than "2". I cannot find such a font in my system (Manjaro).
Maybe someone just knows the font name.

**Comment by hanna-kn** [comment]
Sabon
