### ISSUE TITLE
[1.5.3] Linux binary archive crashes bsdtar

### ISSUE THREAD

**Issue by nils-van-zuijlen** [Eqonomize/Eqonomize#135]
Hello,

I'm trying to update the AUR package for eqonomize, but I got stuck because `bsdtar`, the uncompressing software used by `makepkg` crashes trying to extract the archive contents.

It does it for both the 32 and 64 bits archives, it does not do it for the 1.5.2 archives.

Here are its "verbose" logs:
```
bsdtar: Archive entry has empty or unreadable filename ... skipping.
x eqonomize
bsdtar: Error exit delayed from previous errors.
```

Strangely enough, it does extract the program, which is runnable, but crashes with the following error, although that lib is installed on my machine, in `/usr/lib/libQt5PrintSupport.so.5`.

```
./eqonomize: error while loading shared libraries: libQt5PrintSupport.so.5: cannot open shared object file: No such file or directory
```

PS: it would be really nice if you published official checksums for the archives, I'm currently computing them myself for the packaging.

**Comment by nils-van-zuijlen** [comment]
Oops, I can confirm that the extracted program does run properly, if extract the right architecture for your system (64bits in my case)

**Comment by nils-van-zuijlen** [comment]
By listing the archive's contents with `tar -tvf`, I got the following output, meaning that the first file in these archives does not have a name, and that is what crashes bsdtar.

```
tar: Remplacement des noms vides par « . » pour les membres
drwx------ hanna/hanna       0 2021-12-29 16:13 
-rwxrwxr-x hanna/hanna 8558104 2021-12-29 16:09 eqonomize
```

May I suggest using the following tarballs, which should extract the same binary, and not crash `bsdtar`?

[eqonomize-1.5.3-i386-fixed.tar.gz](https://github.com/Eqonomize/Eqonomize/files/7904344/eqonomize-1.5.3-i386-fixed.tar.gz)
[eqonomize-1.5.3-x86_64-fixed.tar.gz](https://github.com/Eqonomize/Eqonomize/files/7904345/eqonomize-1.5.3-x86_64-fixed.tar.gz)

**Comment by hanna-kn** [comment]
I've replaced the tarballs with versions without entry with empty or unreadable filename. The problematic tarballs were created using file-roller by the replacing file in an old archive.

**Comment by nils-van-zuijlen** [comment]
Thanks, it works!
