### ISSUE TITLE
Win 10 dark mode import

### ISSUE THREAD

**Issue by Li-An** [Eqonomize/Eqonomize#139]
Hello, in Win 10, in dark mode, the text in nature selection is not showing. I had to go back to default view to see the options.

**Comment by Li-An** [comment]
Sorry, I should have attached a screen capture. When I try to import a file, here is the window
[![Image](https://i.goopics.net/rfm51c.png)](https://goopics.net/i/rfm51c)

**Comment by hanna-kn** [comment]
Fixed.

**Comment by Li-An** [comment]
Thanks a lot.
