### ISSUE TITLE
Creating new document leads to Segmentation fault

### ISSUE THREAD

**Issue by vnnv** [Eqonomize/Eqonomize#14]
Latest version - master - click new from the toolbar or File - New from the menu or Ctrl-N leads to crash - Segmentation fault (core dumped)

**Comment by hanna-kn** [comment]
It also often (but not always) crashes when opening another file (but it is opened without any issue when restarting the application). I've actually experienced this for a while now, but I guess I should try to fix it soon.

**Comment by vnnv** [comment]
Yes, sometimes crashes when open new file :)

**Comment by hanna-kn** [comment]
It should hopefully be fixed now.

**Comment by vnnv** [comment]
Much more stable is now. It crashed 1 time when I choose document from Recent menu, but most of the time is ok.
