### ISSUE TITLE
Make issue

### ISSUE THREAD

**Issue by selfus** [Eqonomize/Eqonomize#15]
Getting error when using make on the latest commit

> src/categoriescomparisonchart.cpp: In member function ‘void CategoriesComparisonChart::updateDisplay()’:
src/categoriescomparisonchart.cpp:1063:113: error: ‘budhet’ was not declared in this scope
   QGraphicsSimpleTextItem *legend_text = new QGraphicsSimpleTextItem(QString("%1 (%2%)").arg(legend_string).arg(budhet->formatMoney(legend_value, deci, false)));
                                                                                                                 ^
Makefile:545: recipe for target 'build/categoriescomparisonchart.o' failed
make: *** [build/categoriescomparisonchart.o] Error 1

**Comment by hanna-kn** [comment]
I simple typo, undiscovered when compiled with QtCharts (compilation without QtCharts enabled is not recommended, and will eventually be unsupported, although I understand that the module might not yet be available for all distributions).

**Comment by selfus** [comment]
Thanks.

Hope it gets to Kubuntu soon QTcharts
