### ISSUE TITLE
[FR] Unrealized Gains/Losses for Non-Security Assets

### ISSUE THREAD

**Issue by DominiqueSite** [Eqonomize/Eqonomize#159]
For some assets (non-securities like gold or fine art), one has to manually input the unrealized gains or losses by adjusting the opening balance for Eqonomize to reflect the current asset distribution. This can be solved by implementing a feature that allows one to manually set unrealized gains/losses for non-security assets, similar to "Set Quote" for securities.

**Comment by hanna-kn** [comment]
I would recommend adding such as assets as securities in Eqonomize.
