### ISSUE TITLE
Wrong value in ledger view when currencies are used

### ISSUE THREAD

**Issue by vnnv** [Eqonomize/Eqonomize#16]
Here is an example
1. From USD account I transfer 107$ and get 100€ in Euro account.
When I open ledger view and select USD account the value is 100$ but when I chage the view to see Euro account transacations the value is again 100 (€) instead of 107 (€)

**Comment by hanna-kn** [comment]
Fixed.

**Comment by vnnv** [comment]
You rock! Works!
