### ISSUE TITLE
No subtotal when view expenses by parent catergories in catergories comparison report

### ISSUE THREAD

**Issue by Chr1sDewhurst** [Eqonomize/Eqonomize#161]
When I view top level expense categories in the categories comparison report, there is no subtotal for each month. See attached PDF export. I am using the latest windows download

[No subtotal bug.pdf](https://github.com/Eqonomize/Eqonomize/files/11438479/No.subtotal.bug.pdf)

**Comment by hanna-kn** [comment]
Fixed.

**Comment by Chr1sDewhurst** [comment]
Appreciate the fast response! To implement the fix, I imagine I'll need to compile it from the source code myself rather than using the installer? Don't suppose there's an easy way to do this?

**Comment by hanna-kn** [comment]
> Don't suppose there's an easy way to do this?

Not that I'm aware of.

Note that the same data is available using the development over time report (with rows and columns switched, and no option to specify a date range).

**Comment by Chr1sDewhurst** [comment]
No worries! Will have a poke about and see if I can figure it out when I have more time. Thanks again for the ongoing support on this project! Best finance software I've been able to find!
