### ISSUE TITLE
Editing transfer with currencies - wrong value in withdrawal amount

### ISSUE THREAD

**Issue by vnnv** [Eqonomize/Eqonomize#17]
If you try to edit existing currency transfer - deposit amount is the same as withdrawal.

**Comment by hanna-kn** [comment]
Fixed. (There are probably many of these serious but easily fixable bugs left, because of lack of testing after fast coding.)

**Comment by vnnv** [comment]
I'll try to find these little bugs :) I am reworking my currency transactions :) 
I am not familiar with the code yet to make pull requests :)
