### ISSUE TITLE
A portable version

### ISSUE THREAD

**Issue by ags1234** [Eqonomize/Eqonomize#176]
A zip archive with all necessary files, without C++ framework.
A mechanism for the program to know to run as portable and rely only on current directory. Could be the presence of an empty file named "portable".

**Comment by hanna-kn** [comment]
Done: https://github.com/Eqonomize/eqonomize/releases/download/v1.5.7/eqonomize-1.5.7-x64.zip

**Comment by ags1234** [comment]
Thanks, I see the solution was to make an empty directory named "user".  Nice!

**Comment by hanna-kn** [comment]
> Thanks, I see the solution was to make an empty directory named "user".

It is not enough to create a "user" directory. The code was modified to use the specific directory.

**Comment by ags1234** [comment]
Of course, I did not want to imply that it was only about creating a directory.
I appreciate your willingness to adapt and change the code. Thanks again.
