### ISSUE TITLE
Where can I download latest nightly build?

### ISSUE THREAD

**Issue by Darthagnon** [Eqonomize/Eqonomize#186]
Hello, following a few issues that I had being solved in recent commits, I was wondering if there was somewhere I could download a binary build of the latest nightly? or if there was a new release coming out any time soon?

**Comment by hanna-kn** [comment]
Version [1.5.8](https://github.com/Eqonomize/Eqonomize/releases/tag/v1.5.8) has now been released.

**Comment by Darthagnon** [comment]
Thank you!
