### ISSUE TITLE
Recurring Security Shares Purchases

### ISSUE THREAD

**Issue by culso** [Eqonomize/Eqonomize#188]
Would it be possible to add securities transactions to schedules? For example buying shares on a monthly basis.

Some banks offer savings plans, e.g. for ETFs. This way, for a fixed amount (e.g. 100€), shares are bought on the 1st of every month.

The only problem I see is that Eqonomize does not know the quote/price of a security when it is bought. The program could use the most recent quote from the file and the user would subsequently enter the actual quote at which the shares were bought.

**Comment by hanna-kn** [comment]
It is already possible (even though the option to create a security transaction is not present in the New Schedule menu).

![Skärmbild_20241111_123311](https://github.com/user-attachments/assets/da806125-4cbf-4284-9793-6cbcf82bca5c)

**Comment by culso** [comment]
How could I have missed that! That's perfect!

Thank you :)
