### ISSUE TITLE
Launching with translation?

### ISSUE THREAD

**Issue by tr37ion** [Eqonomize/Eqonomize#2]
Usually I start applications in another language by eg. `LANGUAGE=es_ES LANG=es_ES eqonomize %U`.
Actually, this doesn't work with Eqonomize.

**Comment by hanna-kn** [comment]
It works for me. 
Are you using the source tarball for version 1.0-beta1 or the git version?
Is the translation file (eqonomize_es.qm) installed correctly in $PREFIX/share/eqonomize/translations/?

**Comment by tr37ion** [comment]
I'm using the git repo on Arch. Where is the path $PREFIX/share/eqonomize/translations/ supposed to be?

**Comment by hanna-kn** [comment]
The default path is /usr/local/share/eqonomize/translations/.

When using the git repo you need to run `lrelease Eqonomize.pro`after `qmake`, to generate the binary translation files (in accordance with the installation instructions).

**Comment by gityeti** [comment]
Bonjour hanna-kn, and thx for your great job! 
I can't launch eqonomize in french. I installed eqonomize on debian. it appears in english. I coudn't find the translations file, neither with dpgk -L eqonomize, nor in /usr/share/eqonomize where there is just the currencies.xml file. So I created that directory and put (past) the file in :
/usr/share/eqonomize# mkdir translations
/usr/share/eqonomize# cd translations/
/usr/share/eqonomize/translations# nano eqonomize_fr.ts
So the file is there, but I can't get the programm run in french.
Thx for your help.

**Comment by hanna-kn** [comment]
> I can't launch eqonomize in french. I installed eqonomize on debian. it appears in english. I coudn't find the translations file, neither with dpgk -L eqonomize, nor in /usr/share/eqonomize where there is just the currencies.xml file. So I created that directory and put (past) the file in :
> /usr/share/eqonomize# mkdir translations
> /usr/share/eqonomize# cd translations/
> /usr/share/eqonomize/translations# nano eqonomize_fr.ts
> So the file is there, but I can't get the programm run in french.

eqonomize_fr.**qm** is required and not the .ts file. 

It does however seem as if the old unfinished French documentation (which should ideally not be installed) is included in the eqonomize-doc package.

This is likely caused by Debian not using the official source package (they are instead using the automatically generated Git package).

You should report this as a bug in Debian.
