### ISSUE TITLE
Missing files - can not compile

### ISSUE THREAD

**Issue by vnnv** [Eqonomize/Eqonomize#21]
> qmake Eqonomize.pro
WARNING: Failure to find: src/currencyconversiondialog.cpp
WARNING: Failure to find: src/currencyconversiondialog.h

**Comment by hanna-kn** [comment]
Fixed (it's easy to forget adding new files to git).

**Comment by vnnv** [comment]
I use git bash prompt for this :) It is very helpful, all information about current repo - such as changed files, not tracked files, etc. can be in the bash prompt
