### ISSUE TITLE
Flatpak or AppImage

### ISSUE THREAD

**Issue by baimafeima** [Eqonomize/Eqonomize#22]
Could you add Flatpak to your next release here on GitHub?
http://flatpak.org/

**Comment by hanna-kn** [comment]
Unfortunately there does not seem to be a stable Flatpak runtime for Qt apps available yet.

**Comment by baimafeima** [comment]
@hanna-kn Is this helpful? https://community.kde.org/Guidelines_and_HOWTOs/Flatpak#Qt_and_KF5_Runtime

**Comment by baimafeima** [comment]
I think there is not much movement with Flatpak. Alternatively, it would be interesting to explore whether an AppImage release is possible. I know that @probonopd of AppImage is very helpful.

**Comment by probonopd** [comment]
Check https://github.com/Eqonomize/Eqonomize/pull/29.
