### ISSUE TITLE
eqonomize

### ISSUE THREAD

**Issue by uprokop** [Eqonomize/Eqonomize#25]
Very, very good software, the best I know in this section! Congratulations!
I am using the version 1.0 beta 2 on Ubuntu 16.04 - without installation; Almost everything runs error-free, but when I choose print preview, the program is terminated - that's probably so not planned.
If you give me your bank account, I would like to donate a little - not as a payment but as a recognition and motivation for your great work!

**Comment by hanna-kn** [comment]
Thanks!
The print preview issue has already been fixed. 
I added a donation button at the end of the project page.
