### ISSUE TITLE
Exchange rate of newly added currency is incorrect!

### ISSUE THREAD

**Issue by sulemankm** [Eqonomize/Eqonomize#27]
Hi, I've added my currency to the 1.0-beta3 version.  Firstly, the new currency did not appear in the currency converter until after I closed and reopened the program.  Secondly and more importantly, the exchange rate of the new currency is incorrect, despite updating exchange rates many times.

I added the following currency, { Code: PKR, Symbol: PKR, Name: Pakistani Rupee}.

I'm on windows 10 (if that makes any difference).

**Comment by hanna-kn** [comment]
Eqonomize! cannot update the exchange rate that you add yourself (that is not available in the data from the European central bank). You will have to update the exchange rate manually (using edit currency button in edit account window).

The issue with the currencies conversion list not updating immediately has now been fixed.

**Comment by hanna-kn** [comment]
Support for PKR and many other currencies has now been added.
