### ISSUE TITLE
impaird vision

### ISSUE THREAD

**Issue by uprokop** [Eqonomize/Eqonomize#31]
I am of impaird vision and need some help. 
Is it possible to enlarge view or increase contrast?

For me it would be a substantial improvement, may be it would comfort some other.

**Comment by hanna-kn** [comment]
Eqonomize! follows the settings of the desktop environment and/or KDE/Qt. If you are using Unity on Ubuntu you can change to high contrast theme under System Settings->Appearance and increase the font size using Unity Tweak Tool.
