### ISSUE TITLE
Statistics Comparison Categories Chart doesn't work for incomes

### ISSUE THREAD

**Issue by albertforU** [Eqonomize/Eqonomize#34]
While selecting Comparison Categories Chart I can properly see the chart with Expenses (Gastos report-2) but if I select All Incomes (Ingresos  report-3) with or without categories the period selector filter turns to grey and doesn't show the different incomes.

![report-3](https://user-images.githubusercontent.com/33034439/31911971-b7323bba-b842-11e7-8f47-2a5485c0f7c7.png)
![report-2](https://user-images.githubusercontent.com/33034439/31911973-b7570440-b842-11e7-9667-3957fd155b31.png)
![report-1](https://user-images.githubusercontent.com/33034439/31911974-b776ed64-b842-11e7-9e90-b3784b0f8f21.png)

**Comment by hanna-kn** [comment]
Should be fixed now.

You can download the fixed AppImage here:
https://github.com/Eqonomize/Eqonomize/releases/download/v1.0.0/Eqonomize-git.AppImage
