### ISSUE TITLE
Categories comparison REPORT and CHART incorrects with "All categories WITH subcategories"

### ISSUE THREAD

**Issue by albertforU** [Eqonomize/Eqonomize#36]
When you choose Categories Comparison Report the Income and Expenses are added twice in the all categories WITH subcategories.
A similar problem is observed with the same choice (All categories WITH subcategories) in the Categories Comparison CHART. In this case any chart is represented

**Comment by hanna-kn** [comment]
Issue with report has been fixed.

It seems as if you did not finish the sentence about the chart issue. 
I cannot find any issue with the chart similar to the one for the report. (It can however be a bit confusing that the percentage of a subcategory may be greater than of the parent category; the parent category does in this case only include transactions without a subcategory).

**Comment by albertforU** [comment]
The Categories Comparison Report has been fixed. The other persist.
Is in the Categories Comparison Chart when you choose the filter "All categories WITH subcategories". The response is a blank chart (No chart). All the other filters seems to work properly

**Comment by albertforU** [comment]
Otherwise the program is very clear, precise, simply and easy. I'm using it for a little Non Profit Association instead of a spreadsheet.
Thanks

**Comment by albertforU** [comment]
Otherwise the program is clear, precise, simply and easy. I'm using it for a little non profit association instead of a spreadsheet.
Thanks

**Comment by hanna-kn** [comment]
> Is in the Categories Comparison Chart when you choose the filter "All categories WITH subcategories". The response is a blank chart (No chart).
Now fixed.
