### ISSUE TITLE
Impossible d'installer sur windows si le redistribuable VC++ est deja présent - v 1.0 release

### ISSUE THREAD

**Issue by malickf** [Eqonomize/Eqonomize#37]
Je viens d'essayer d'installer le logiciel (windows binary téléchargé ici : https://eqonomize.github.io/downloads.html ) sans succès car j'ai déjà le redistribuable VC++ x86 sur mon ordinateur, L'installation du redistribuable me dit que ce n'est pas possible car j'ai déjà une version version plus récente :  
`[15A8:0F34][2017-10-27T11:32:06]e000: Error 0x80070666: Cannot install a product when a newer version is installed.`
Du coup l'installateur de Eqonomize considère qu'il y a une erreur et l'installation est annulée.

Log d'erreur : 

The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 1 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 6.1.0 {version}
Running checks for package 'Visual C++ "14" Runtime Libraries (x86)', phase BuildList
Running MsiProductCheck with ProductCode '{BBF2AC74-720C-3CB3-8291-5E34039232FA}'
MsiQueryProductState returned '-1'
Setting value '-1 {int}' for property 'VCRedistInstalled'
The following properties have been set for package 'Visual C++ "14" Runtime Libraries (x86)':
Property: [VCRedistInstalled] = -1 {int}
Running checks for command 'vcredist_x86\vcredist_x86.exe'
Result of running operator 'ValueGreaterThanEqualTo' on property 'VCRedistInstalled' and value '3': false
Result of running operator 'ValueEqualTo' on property 'AdminUser' and value 'false': false
Skipping FailIf because Property 'Version9X' was not defined
Result of running operator 'VersionLessThan' on property 'VersionNT' and value '6.00': false
Result of checks for command 'vcredist_x86\vcredist_x86.exe' is 'Install'
'Visual C++ "14" Runtime Libraries (x86)' RunCheck result: Install Needed
Installation of components 'Visual C++ "14" Runtime Libraries (x86)' was accepted.
Copying files to temporary directory "C:\Users\Malick\AppData\Local\Temp\VSDA27E.tmp\"
Downloading files to "C:\Users\Malick\AppData\Local\Temp\VSDA27E.tmp\"
(27/10/2017 11:32:02) Downloading 'vcredist_x86\vcredist_x86.exe' from 'http://go.microsoft.com/fwlink/?LinkID=800028&clcid=0x409' to 'C:\Users\Malick\AppData\Local\Temp\VSDA27E.tmp\'
Download completed at 27/10/2017 11:32:02
Verifying file integrity of C:\Users\Malick\AppData\Local\Temp\VSDA27E.tmp\vcredist_x86\vcredist_x86.exe
WinVerifyTrust returned 0
File trusted
Running checks for package 'Visual C++ "14" Runtime Libraries (x86)', phase BeforePackage
Running MsiProductCheck with ProductCode '{BBF2AC74-720C-3CB3-8291-5E34039232FA}'
MsiQueryProductState returned '-1'
Setting value '-1 {int}' for property 'VCRedistInstalled'
The following properties have been set for package 'Visual C++ "14" Runtime Libraries (x86)':
Property: [VCRedistInstalled] = -1 {int}
Running checks for command 'vcredist_x86\vcredist_x86.exe'
Result of running operator 'ValueGreaterThanEqualTo' on property 'VCRedistInstalled' and value '3': false
Result of running operator 'ValueEqualTo' on property 'AdminUser' and value 'false': false
Skipping FailIf because Property 'Version9X' was not defined
Result of running operator 'VersionLessThan' on property 'VersionNT' and value '6.00': false
Result of checks for command 'vcredist_x86\vcredist_x86.exe' is 'Install'
'Visual C++ "14" Runtime Libraries (x86)' RunCheck result: Install Needed
Verifying file integrity of C:\Users\Malick\AppData\Local\Temp\VSDA27E.tmp\vcredist_x86\vcredist_x86.exe
WinVerifyTrust returned 0
File trusted
Installing using command 'C:\Users\Malick\AppData\Local\Temp\VSDA27E.tmp\vcredist_x86\vcredist_x86.exe' and parameters ' /q:a '
Process exited with code 1638
Status of package 'Visual C++ "14" Runtime Libraries (x86)' after install is 'InstallFailed'

J'ai pu installer sans problème la version 1.0 beta 3.

En tout cas merci pour le partage !

**Comment by hanna-kn** [comment]
I have made the pure installer file, which should avoid this issue, available here:
https://github.com/Eqonomize/eqonomize/releases/download/v1.0.0/eqonomize-1.0.msi

**Comment by malickf** [comment]
Woooh sorry, I though you were French, I just realized my mistake with your answer ^^ 
Thanks for the new link, I have just tried it and it did works indeed. 
Greetings

**Comment by malickf** [comment]
Grattis för att du förstår mig på franska (och för det snabba svaret) :-)
