### ISSUE TITLE
Eqonomize won't install in Windows 10

### ISSUE THREAD

**Issue by Ridbowt** [Eqonomize/Eqonomize#45]
Hi!

![image](https://user-images.githubusercontent.com/37126465/37066163-1a5bb2e4-21b5-11e8-92e7-1b7a63af8388.png)

![image](https://user-images.githubusercontent.com/37126465/37066284-c6c6415c-21b5-11e8-9367-84164046b106.png)

`[A764:A8C0][2018-03-07T03:06:47]i001: Burn v3.7.3813.0, Windows v10.0 (Build 14393: Service Pack 0), path: C:\Users\nix\AppData\Local\Temp\VSD154A.tmp\vcredist_x86\vcredist_x86.exe, cmdline: '/q:a  -burn.unelevated BurnPipe.{BFE74B70-8D26-48EE-86A8-71D027A50D1B} {CC34D08F-9C66-46E9-83CD-ABEF000C3C6E} 3040'
[A764:A8C0][2018-03-07T03:06:47]i000: Setting string variable 'WixBundleLog' to value 'C:\Users\nix\AppData\Local\Temp\dd_vcredist_x86_20180307030647.log'
[A764:A8C0][2018-03-07T03:06:47]i000: Setting string variable 'WixBundleOriginalSource' to value 'C:\Users\nix\AppData\Local\Temp\VSD154A.tmp\vcredist_x86\vcredist_x86.exe'
[A764:A8C0][2018-03-07T03:06:47]i000: Setting string variable 'WixBundleOriginalSourceFolder' to value 'C:\Users\nix\AppData\Local\Temp\VSD154A.tmp\vcredist_x86\'
[A764:A8C0][2018-03-07T03:06:47]i000: Setting string variable 'WixBundleName' to value 'Microsoft Visual C++ 2017 Redistributable (x86) - 14.10.25008'
[A764:A8C0][2018-03-07T03:06:47]i100: Detect begin, 10 packages
[A764:A8C0][2018-03-07T03:06:47]i000: Setting version variable 'windows_uCRT_DetectKey' to value '10.0.14393.2097'
[A764:A8C0][2018-03-07T03:06:47]i000: Setting numeric variable 'windows_uCRT_DetectKeyExists' to value 1
[A764:A8C0][2018-03-07T03:06:47]i107: Detected forward compatible bundle: {5c045b7f-e561-4794-91f8-c6cda0893107}, type: Upgrade, scope: PerMachine, version: 14.13.26020.0, enabled: No
[A764:A8C0][2018-03-07T03:06:47]i102: Detected related bundle: {5c045b7f-e561-4794-91f8-c6cda0893107}, type: Upgrade, scope: PerMachine, version: 14.13.26020.0, operation: Downgrade
[A764:A8C0][2018-03-07T03:06:47]i108: Detected compatible package: vcRuntimeMinimum_x86, provider: Microsoft.VS.VC_RuntimeMinimumVSU_x86,v14, installed: {8F271F6C-6E7B-3D0A-951B-6E7B694D78BD}, version: 14.13.26020, chained: {C6CDA568-CD91-3CA0-9EDE-DAD98A13D6E1}
[A764:A8C0][2018-03-07T03:06:47]i103: Detected related package: {8F271F6C-6E7B-3D0A-951B-6E7B694D78BD}, scope: PerMachine, version: 14.13.26020.0, language: 0 operation: Downgrade
[A764:A8C0][2018-03-07T03:06:47]i108: Detected compatible package: vcRuntimeAdditional_x86, provider: Microsoft.VS.VC_RuntimeAdditionalVSU_x86,v14, installed: {895D5198-C5DB-375E-86AB-133F4DAA9FE2}, version: 14.13.26020, chained: {E6222D59-608C-3018-B86B-69BD241ACDE5}
[A764:A8C0][2018-03-07T03:06:47]i103: Detected related package: {895D5198-C5DB-375E-86AB-133F4DAA9FE2}, scope: PerMachine, version: 14.13.26020.0, language: 0 operation: Downgrade
[A764:A8C0][2018-03-07T03:06:47]i052: Condition '(VersionNT = v6.3 AND NOT VersionNT64) AND (windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10240.0)' evaluates to false.
[A764:A8C0][2018-03-07T03:06:47]i052: Condition '(VersionNT = v6.3 AND VersionNT64) AND (windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10240.0)' evaluates to false.
[A764:A8C0][2018-03-07T03:06:47]i052: Condition '(VersionNT = v6.2 AND NOT VersionNT64) AND (windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10240.0)' evaluates to false.
[A764:A8C0][2018-03-07T03:06:47]i052: Condition '(VersionNT = v6.2 AND VersionNT64) AND (windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10240.0)' evaluates to false.
[A764:A8C0][2018-03-07T03:06:47]i052: Condition '(VersionNT = v6.1 AND NOT VersionNT64) AND (windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10240.0)' evaluates to false.
[A764:A8C0][2018-03-07T03:06:47]i052: Condition '(VersionNT = v6.1 AND VersionNT64) AND (windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10240.0)' evaluates to false.
[A764:A8C0][2018-03-07T03:06:47]i052: Condition '(VersionNT = v6.0 AND NOT VersionNT64) AND (windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10240.0)' evaluates to false.
[A764:A8C0][2018-03-07T03:06:47]i052: Condition '(VersionNT = v6.0 AND VersionNT64) AND (windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10240.0)' evaluates to false.
[A764:A8C0][2018-03-07T03:06:47]i101: Detected package: vcRuntimeMinimum_x86, state: Obsolete, cached: None
[A764:A8C0][2018-03-07T03:06:47]i101: Detected package: vcRuntimeAdditional_x86, state: Obsolete, cached: None
[A764:A8C0][2018-03-07T03:06:47]i101: Detected package: Windows81_x86, state: Absent, cached: None
[A764:A8C0][2018-03-07T03:06:47]i101: Detected package: Windows81_x64, state: Absent, cached: None
[A764:A8C0][2018-03-07T03:06:47]i101: Detected package: Windows8_x86, state: Absent, cached: None
[A764:A8C0][2018-03-07T03:06:47]i101: Detected package: Windows8_x64, state: Absent, cached: None
[A764:A8C0][2018-03-07T03:06:47]i101: Detected package: Windows7_MSU_x86, state: Absent, cached: None
[A764:A8C0][2018-03-07T03:06:47]i101: Detected package: Windows7_MSU_x64, state: Absent, cached: None
[A764:A8C0][2018-03-07T03:06:47]i101: Detected package: WindowsVista_MSU_x86, state: Absent, cached: None
[A764:A8C0][2018-03-07T03:06:47]i101: Detected package: WindowsVista_MSU_x64, state: Absent, cached: None
[A764:A8C0][2018-03-07T03:06:47]i052: Condition 'VersionNT >= v6.0 OR (VersionNT = v5.1 AND ServicePackLevel >= 2) OR (VersionNT = v5.2 AND ServicePackLevel >= 1)' evaluates to true.
[A764:A8C0][2018-03-07T03:06:47]i199: Detect complete, result: 0x0
[A764:ACDC][2018-03-07T03:06:52]e000: Error 0x80070666: Cannot install a product when a newer version is installed.
`

**Comment by Ridbowt** [comment]
I installed the program, anyhow. I extracted **eqonomize-1.2.msi** with help of _UniExtract_ and did it.

**Comment by hanna-kn** [comment]
I have now replace eqonomize-1.2.exe with eqonomize-1.2.msi and instead added a link to Visual C++ redistributable, since these problems a recurring and seems difficult to avoid when using Visual Studio Installer Projects extensions.

**Comment by sergeevabc** [comment]
Oh, @hanna-kn, why did you move to QT6… As a result, Eqonomize cannot be used in parts of the world where people continue to use Windows 7.

**Comment by hanna-kn** [comment]
> Oh, @hanna-kn, why did you move to QT6… As a result, Eqonomize cannot be used in parts of the world where people continue to use Windows 7.

The 32-bit version (compiled with Qt5) can still be used with Windows 7.

**Comment by sergeevabc** [comment]
I confirm that Eqonomize 1.5.6 x86 runs on Windows 7 x64. Perhaps it's worth making it clear on the [Downloads](http://eqonomize.github.io/downloads.html) page that x86 version is the lifeline for vintage OS users.

![2024-0122-0008 eqonomize windows7](https://github.com/Eqonomize/Eqonomize/assets/373718/6a7f4306-be81-4407-b246-49e07cebc74b)

**Comment by sergeevabc** [comment]
Dear @hanna-kn, how do I turn Eqonomize **x86** (with Windows 7 support) to portable so that data is written in the app's folder, not in the Windows user's profile?

**Comment by hanna-kn** [comment]
> Dear [@hanna-kn](https://github.com/hanna-kn), how do I turn Eqonomize **x86** (with Windows 7 support) to portable so that data is written into the app's folder, not into Windows user's profile?

Uncomment `#define PACKAGE_PORTABLE 1` on line 53 in src/budget.h. This requires that you compile Eqonomize yourself.
