### ISSUE TITLE
Compiling for Linux (Newbie)

### ISSUE THREAD

**Issue by Tr1ck5t3rJLW** [Eqonomize/Eqonomize#5]
I am fairly new to Linux and have never been able to install from a .tar.gz file. What I have found on Youtube says I need to run a configure file. I have not been able to find such a file in your package. I also have not been able to find instructions on how to install on your web site. If I have overlooked these instructions I apologize. Said instructions specific to your software would be extremely helpful for a newbie such as myself.

**Comment by hanna-kn** [comment]
Installation instructions are available at https://github.com/Eqonomize/Eqonomize#installation and in README.md in the .tar.gz file (which first should be extracted).

**Comment by Tr1ck5t3rJLW** [comment]
Thank you

**Comment by selfus** [comment]
Instead of using make install, use sudo checkinstall

May need to install checkinstall first.
