### ISSUE TITLE
Multilanguage version

### ISSUE THREAD

**Issue by Elio1944** [Eqonomize/Eqonomize#74]
I Have downloaded Eqonomize and have been trying to use it for a couple of months.
The problem I am encountering is that it is half in english and half in italian (labels and help)
How can I downgrade to a complete english version?
In future I coul help to complete the italian version, but I shoul be able to understande bettere the core versione, which I assume is in english.
Thankyou very much.

**Comment by hanna-kn** [comment]
I assume that you are using Windows (if you are using GNU/Linux run the application from terminal with `LANG=en_US eqonomize`).

I have now added language selection to the settings menu. I've compiled a new Windows binary, with this feature included, which you can download at https://0x0.st/zoiz.zip (sha256: 4c51faabad2064ccb23c881d589d164ceac15edb3c847847446d2f18a57625da). Extract eqonomize.exe and replace the installed binary (c:\Program Files (x86)\Eqonomize\eqonomize.exe).
