### ISSUE TITLE
Categories in Assets and Liabilities

### ISSUE THREAD

**Issue by vnnv** [Eqonomize/Eqonomize#75]
Hello @hanna-kn, 
This is an enhancement idea. 
Is it possible to add categories in `Assets` and `Liabilities` just like in `Incomes` and `Expenses`. 

If such option exists one can group all banks accounts and cash accounts in groups. The same is  for loans - you can group all your credit cards, stock loans/mortgages.

**Comment by vnnv** [comment]
Hello, any chance for a comment :)

**Comment by hanna-kn** [comment]
I am considering it...

It would not be complicated to implement, but requires a not insignificant amount of work.
I doubt that there are many user with enough accounts for this to be useful.

**Comment by vnnv** [comment]
I think automatic based on account type is ok :) Personally I have 20 accounts. :)

**Comment by hanna-kn** [comment]
Done.

**Comment by vnnv** [comment]
Thank you very much! :)
