### ISSUE TITLE
No cents allowed

### ISSUE THREAD

**Issue by eqoeqo** [Eqonomize/Eqonomize#76]
I have just installed Eqonomize on Ubuntu Studio 18.10.  The currency is ZAR.  I cannot enter any cents on any transaction.  If I put in cents, the figure changes to 0.00.

I really, really want this to be a fabulous program :-)  I am trying to move away from QuickBooks (and all things Win), and your program is the first one I've found that autofills transactions and payee/payer names and categories etc. etc., which is the main reason I've stayed with my antique QB for so long.

Thank you so much for creating this program :smile:

**Comment by hanna-kn** [comment]
Try using comma as decimal separator instead (QLocale().decimalPoint() returns ',' for en_ZA). Eqonomize lacks proper support for locales which uses both comma and dot as decimal separator.

I've now add support for dot as alternative decimal separator, for locales with decimal comma and without dot as group separator (an updated AppImage binary as available at https://transfer.sh/WERvG/Eqonomize-git.4a1cb19-x86_64.AppImage).

**Comment by eqoeqo** [comment]
Oh, brilliant, thank you!  The appimage works with decimal point.  (But the text is tiny, is there anyway to increase font size?)  Using a number keypad means that using commas would slow me down and drive me crazy!  All southern African currencies (ZARands, Zim dollars, Namibian dollars, Pula, Emalangeni etc.) use a point not a comma.  Is the comma an Ubuntu locale issue?

And can I change the code somewhere myself?  I'd like to fix the standard program on my computer so that I can use the bigger font size...

**Comment by hanna-kn** [comment]
I had not considered the case where monetary values use a different decimal separator. I should be able to fix that, but it will have to wait until tomorrow. 

The font size is an AppImage issue. The font size is not specified in the code and should normally follow system font size preferences. You can try running the AppImage with QT_STYLE_OVERRIDE=GTK+ (it did however not work for me).

**Comment by eqoeqo** [comment]
Thank you, Hanna :-)

Let me know when there is a fix/patch, please.  I have not had time to play around with the Qt yet.  Just for interest's sake: the Ubuntu locale ZA has the decimal point as default, which is good to know.

**Comment by hanna-kn** [comment]
Format for monetary values should now be improved (although more testing is needed).

Updated AppImage: https://transfer.sh/c2wNg/Eqonomize-git.551fa48-x86_64.AppImage

**Comment by hanna-kn** [comment]
The main issue seems to be confusion regarding the appropriate decimal separator in South Africa.
- glibc uses decimal point (for both monetary and general numbers)
- Qt uses decimal comma (so does also ICU, FreeBSD, ...)
- According to Wikipedia both is used, but the decimal separator articles state that when "South Africa adopted the metric system, it adopted the comma as its decimal separator".

The previous changes in Eqonomize resultet (on Linux) in the use decimal point for monetary values, but decimal comma for other numbers. I have now made changes so that all numbers are formatted according to localeconv() values (from glibc on Linux).

**Comment by eqoeqo** [comment]
Thank you so much :-)

There is no confusion in South Africa itself, we all use a point.  But there seems to be confusion amongst the programmers (who are probably not South African).

Is this fixed on versions for all platforms?  I ask because some of my clients would benefit from using this program, and I think they're all on Win.  I need a program that has the financial statements and whatnot which Eqonomize doesn't offer (as advertised - I'm not complaining, I'm just giving you the reason why I can't use it as my main accounting program myself).  Please point me in the direction of the Win download.

I am so impressed by your prompt communication, help and fixes!  Thank you so much!

**Comment by hanna-kn** [comment]
> There is no confusion in South Africa itself, we all use a point. But there seems to be confusion amongst the programmers (who are probably not South African).

To me it appears as if the official number format has changed, but that most people still use the old decimal point. This creates a difficult situation for software developers (among which there seems to be a clear trend in favour of the decimal comma).

> Is this fixed on versions for all platforms?

No. The displayed decimal point (and thousands separator) will now follow the system settings (which can be changed by the user). It seems as if the default decimal separator was changed in Windows 8 (and 10), from point to comma. Regardless of which decimal separator is used, it is generally a bad idea for a single program to disregard the system settings.

> Please point me in the direction of the Win download.

https://eqonomize.github.io/downloads.html

**Comment by eqoeqo** [comment]
Thank you!

I think using a comma will not catch on with accountants (and I'm surprised that it is default in some places) - when one is entering figures all day, one uses the number key pad, which has a point and no comma.  Also, it could cause confusion with the comma thousands separator.  But maybe that's just me...?

In any event, thank you for the link, and for all your help and fixes.  And I'm glad the point can be changed by the user on Win :-)

I think we can close this thread now?

**Comment by hanna-kn** [comment]
> I think using a comma will not catch on with accountants (and I'm surprised that it is default in some places) - when one is entering figures all day, one uses the number key pad, which has a point and no comma. Also, it could cause confusion with the comma thousands separator. But maybe that's just me...?

The decimal point is replaced by comma on local keypads (such as on my Swedish keyboard), in which case the opposite is true. (The comma as thousands separator should ideally never be used. Thin space is the recommended standard separator.)
