### ISSUE TITLE
fonts much too small since last update

### ISSUE THREAD

**Issue by uprokop** [Eqonomize/Eqonomize#77]
Since the last update the fonts of the program are much too small for my old eyes. I can't find a way to enlarge the fonts. So I can't use the program, which I like very much, anymore.
I am using Xubuntu 18.04 xfce

**Comment by hanna-kn** [comment]
Are you using the AppImage binary? If that is the case, you should try the other GNU/Linux binary or the snap package (`sudo snap install eqonomize-hk`), or compile it yourself (https://github.com/Eqonomize/eqonomize/releases/download/v1.3.4/eqonomize-1.3.4-x86_64.tar.gz).

**Comment by hanna-kn** [comment]
I've now added font selection to the settings menu (updated AppImage binary is available here: https://transfer.sh/hm0rG/Eqonomize-git.2839c71-x86_64.AppImage).

If you are not using the AppImage binary you should change the desktop font settings. KDE/Qt applications might not follow the Xfce setting, in which case I recommend that you install qt5ct.

**Comment by uprokop** [comment]
Great! I thank you so much.
