### ISSUE TITLE
Error creating SSL context

### ISSUE THREAD

**Issue by uprokop** [Eqonomize/Eqonomize#78]
After updating to xubuntu 19.04 I get the following error message when I want to update the exchange rates: Error creating SSL context

**Comment by hanna-kn** [comment]
The libssl1.0.0 package (required by the AppImage binary) is missing in Ubuntu 19.0.4. It is possible to download and install the package for Ubuntu 18.10 (https://packages.ubuntu.com/cosmic/libssl1.0.0). Ubuntu 19.0.4 does however provide a package for a relatively recent version of Eqonomize (1.3.1).

**Comment by uprokop** [comment]
Thanks for the answer - I need this function very rarely. I don't dare to install the file manually - it doesn't matter, maybe there will be an AppImage in which this function will work again.
