### ISSUE TITLE
CSV-Import: allow fixed category

### ISSUE THREAD

**Issue by Nudin** [Eqonomize/Eqonomize#84]
Currently the value of the category has to be imported from the CSV file. I'd like to use a fixed value as I can for account. I don't see why this value should not be allowed to be set by hand for all entries.

![Bildschirmfoto zu 2019-08-04 21-59-25](https://user-images.githubusercontent.com/509205/62428572-7eb3ac80-b703-11e9-9e0d-b73da983fbf1.png)

**Comment by Nudin** [comment]
I now understood why this limitation is in place: because – if expanse and income are in the same column – we need different category for both.

I still think that it shouldn't be too hard to solve this. For example by adding two inputs one for the expanses and one for incomes. I tried doing it myself but my C++ isn't great and the code is hard to read…

**Comment by Nudin** [comment]
[This is how far I got ](https://github.com/Eqonomize/Eqonomize/compare/master...Nudin:csvimport2?expand=1). I didn't manage to understand the parsing logic.

**Comment by hanna-kn** [comment]
Done.

**Comment by Nudin** [comment]
Oh, wow – your are amassing! Such a fast fix! Thank you so much! <3
