### ISSUE TITLE
Compiling Ubuntu 16.04

### ISSUE THREAD

**Issue by selfus** [Eqonomize/Eqonomize#9]
Hello,

I am having troubles compiling Eqonomize on ubuntu 16.04, getting an error on make.

Any help on this?

**Comment by hanna-kn** [comment]
Have you follow the installation instructions (https://github.com/Eqonomize/Eqonomize#installation)?
What error do you get?

**Comment by selfus** [comment]
I did.
It was an issue with QFileDialog. It seems the qt5 version available on xenial is not capable of handling it well.
After upgrading the qt5 version in my system, I was able to compile it with no issues.

Note: In the instructions, the lrelease command has a typo
