### ISSUE TITLE
Eqonomize installation stumbling at the starting gate under Ubuntu 19.10 Eoan desktop

### ISSUE THREAD

**Issue by baqwas** [Eqonomize/Eqonomize#92]
Hello,

As a beginner I must be making some self-inflicted mistakes in installing the program. I do not wish to call this an issue but more along the lines of FAQ.

After cloning the repository in my folder at _/home/user/projectsEqonomize,_ I change to _/home/user/projects/Eqonomize/src_ and type **qmake**, I receive a message that basically tells me to try again with some additional parameters with the suggestion the -makefile is the default if parameters are omitted (which is what I had done).

How do I gain traction on installing the program under Ubuntu 19.10 Eoan desktop?

Thanks.

P.S. Which **Qt5** packages needed to be installed for full compliance with all features of **Eqonomize**? Perhaps a line or two in a FAQ would be very helpful for novices like myself. Kind regards.

**Comment by hanna-kn** [comment]
In addition to the Qt5 base packages (qtbase5-dev and its dependencies), you will need to packages for the QtCharts module (libqt5charts5 and libqt5charts5-dev).

Unless you wish to contribute to the development of Eqonomize, I suggest that you download the official source package or one of the binary packages from https://eqonomize.github.io/downloads.html.

**Comment by baqwas** [comment]
@hanna-kn,
 
Thx for the quick feedback. I did try the installation of the binary package with elevated privileges under my Ubuntu 19.10 installation with the following two steps which yielded the same error message (_Could not open "**eqonomize**" Archive type not supported_):

1. Ran Archive Manager directly during download
2. Saved archive, extracted and ran the sole file

That is why I thought I would have better luck with the GitHub repository. You are absolute correct in your observation - I am not a Qt developer. (Of course, I am Linux newbie too and therefore really out of my league here). I cannot even pretend that I will be contributing anything to the development of **eqonomize** except, of course, beer money.

I have to migrate from MS Money. After a few months of using GnuCash and KMyMoney, I was looking for something that had investment transactions similar to the limited features in MS Money. Your screen shots and write-up on these desired features appealed to me.

Case closed.

Kind regards.

**Comment by hanna-kn** [comment]
The most convenient option on Ubuntu is usually to install the snap package (using the command `sudo snap install eqonomize-hk` in a terminal window).

**Comment by baqwas** [comment]
Snap (especially the Canonical philosophy that I see being emulated by Azure Sphere) is the best way to ensure traction with advances in computing technology. Unfortunately, I had _self-inflicted_ issues with apps (Arduino & Nextcloud) that makes me subservient to the maxim: _once bitten, twice shy_. The loss is mine entirely. Thank you for your contributions to the needs of so many people globally.

Kind regards.
