### ISSUE TITLE
QFX & OFX import support

### ISSUE THREAD

**Issue by baqwas** [Eqonomize/Eqonomize#93]
Hello,

Apologies for entering this in the issues section but I'm a newbie in these matters.

Is there a published roadmap on support the import of files that are in **QFX** (or even **OFX**) format? Some financial companies only offer **QFX** or **OFX**. I understand that there are commercial converters for this purpose (with caveats, of course).

Kind regards.

P.S. Developer comment on **QIF** in the _official_ _documentation_ noted and appreciated. Thx.

**Comment by hanna-kn** [comment]
There are currently no plans for QFX/OFX support. I do not remember that anyone has requested it before and I have no use for it myself. I will consider this issue as a feature request.

**Comment by baqwas** [comment]
Thanks for the prompt update. **Please consider the matter closed** (no need to log a feature request).

I trust you won't consider me rude (or _obnoxious_) to point out that Citi Cards & AmEx do not support QIF as a download option. The one feature that attracted me to Eqonomize was the ability to track investments. Fidelity and Vanguard provide downloads in OFX format only. Again, I understand that 3rd party converters are available but owing to my lack of experience with these I cannot comment intelligently. Again, apologies for closing out an inquiry in this manner but I really wanted to get away from MS Money and live exclusively in the Linux world.

Kind regards.

**Comment by hanna-kn** [comment]
I consider you neither rude nor obnoxious. It difficult for me to understand the need of users (from different parts of the world, with different financial arrangements, and different book keeping approaches), if they do not tell me. I fully understand that Eqonomize does not (and will never) fit the needs and expectations of all.

Regardless of what you say, I would eventually very much like implement support for OFX (it has after all been on the to do list of the project for a very long time), but unfortunately it appears far from as simple as it was for QIF or CSV files (the OFX specification is almost 700 pages long).
