### ISSUE TITLE
Importing CSV with quoted fields fails

### ISSUE THREAD

**Issue by sirnacnud** [Eqonomize/Eqonomize#94]
I am trying to import a CSV file in which all of the fields have quotes around them. When trying to import the file, I get an error dialog saying invalid values for date and value.

Example entry in the CSV: `"2019-10-01","payee","","description","","category","-10"`

**Comment by hanna-kn** [comment]
I am unable to reproduce this issue with the latest version (1.4.2), using the example entry (imported as expenses and incomes with negative cost). Which version are you using?

**Comment by sirnacnud** [comment]
Trying to import the CSV again, turns out the problem was that I needed to skip the first row in the CSV, as it was the column names, rather than data.

The error I encountered is below. The reason I thought it was the quoted fields, is that the error says all the rows failed to import and I had just imported a different CSV file which didn't have quoted fields successfully. It is a little strange that this first row wasn't just skipped.

```
Unable to import any transactions.
Failed to import 142 data row(s).
-Invalid value.
-Invalid date
```

**Comment by hanna-kn** [comment]
I am unable to reproduce the error, with column names and automatic first row, but if I set the first data row to 1, simulating failure to recognize column names, the date format will be wrong and all rows will fail. It would be helpful if you can provide the contents of the first row (column names) of your CSV file.

**Comment by sirnacnud** [comment]
The first row is:
`"Date","Payee","Account number","Transaction type","Payment reference","Category","Amount (EUR)","Amount (Foreign Currency)","Type Foreign Currency","Exchange Rate"`

**Comment by hanna-kn** [comment]
Unfortunately, there is nothing in the column names that can explain while detection of the first data row fails, and there is no issue when I combine it with the example entry (and similar).

**Comment by sirnacnud** [comment]
Alright, thanks for looking in to this issue. Feel free to close out it.
