### ISSUE TITLE
New Feature - Expense Taxable component.

### ISSUE THREAD

**Issue by warrenc5** [Eqonomize/Eqonomize#95]
Here in Australia we report expenses that have taxable GST/VAT and pay GST accordingly. Expenses without a taxable component are called zero rated expenses.

I would like an option on an expense as to weather it has a taxable component.

Then I can sort and sum zero rated expenses for the purposes of reporting my tax obligations.

I'm happy to submit a merge request, just thought I'd socialize it to see what you think.

**Comment by hanna-kn** [comment]
Can't you use tags for this purpose (e.g. use a "zero rated" tag for zero rated expenses)?

**Comment by warrenc5** [comment]
Hopefully, yes!
Hmm, I've got version 1.3.2 from Debian distro, didn't know about tags. 
Will look at a later version.
