### ISSUE TITLE
Recurring payments with a specified range end too early

### ISSUE THREAD

**Issue by danieltiger47** [Eqonomize/Eqonomize#97]
Hello, Hanna! Thank you for creating this very useful software. It's been amazing to find and start using it -- it's exactly what I've been looking for!

My issue happens when I create a recurring monthly expense or debt payment and specify a range for scheduled recurrence. When I look at a future date (to forecast), the payments appear to stop recurring after two months, rather than following the specified range. Opening the file in a text editor, the correct end date does appear, but it's not reflected within the application's interfaces.

I'm on Linux, if that makes any difference.

Thank you for any assistance you can provide!

**Comment by hanna-kn** [comment]
Fixed.
